#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo ngix -t
sudo service nginx start
