#!/usr/bin/env bash
# Configuring web-01 to have an HTTP response header
# Customising a 404 page. performing a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/AguJP permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

#creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#Configure custom HTTP response header
sudo sed -i "server_name _:/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for syntax errors

sudo nginx -t

#restart nginx after implementing changes

sudo service nginx restart
