#!/usr/bin/env bash
# Create a file /var/run/myscript.pid containing the script PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" on receiving a SIGTERM
# Displays "Y U no love me?!" on receiving a SIGINT
# Deletes the file /var/run/myscript.pid and terminates on SIGQUIT or SIGTERM

terminator() {
  rm /var/frun/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUITgit
done
