#!/usr/bin/env bash
# Display `To infinity and beyond` indefinitely
# with a `sleep 2` after each iteration.
# Display `I am invincible!!! when receiving a SIGTERM signal
var=0
trap 'echo "I am invincible!!!"' SIGTERM
while [ $var ]; do
  echo 'To infinity and beyond'
  sleep 2
done
