#!/usr/bin/env bash
# Print `Best School` 10 times using while loop. print `Hi` after the 9th print
count=0
while [ $count -lt 10 ]
do
if [ $count -eq 9 ]
then
echo "Hi"
fi
echo "Best School"
((count++))
done
