#!/usr/bin/env bash
# SSH configuration file to connect to a server without typing a password
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentifyFile ~/.ssh/school
    PasswordAuthentication no
